### ISSUE TITLE
Mocks in constructor

### ISSUE THREAD

**Issue by DavidGrygar** [mockative/mockative#124]
- I have `classA` that has constructor dependency on `classB`.

- `classB` is class, does not have interface and is annotated with `Mockable` annotation (REEDME instructions) and has its own constructor.

- Now I have test for `classA` but test can't be compiled because problems with automatically generated mock for `classB`.

- Why I need mocks for `classB` when they are not subject of test for `classA`?

- It works when I create Mock from newly created custom interface.

- CI pipelines are ok, and problem is local and flaky.

Usual errors:
- `Unresolved reference: Function0Mock`

- `Base declaration of supertype 'CoroutineDispatcher' needs opt-in. This is an internal kotlinx.coroutines API that should not be used from outside of kotlinx.coroutines. No compatibility guarantees are provided. It is recommended to report your use-case of internal API to kotlinx.coroutines issue tracker, so stable API could be provided instead. The declaration override must be annotated with '@kotlinx.coroutines.InternalCoroutinesApi' or '@OptIn(kotlinx.coroutines.InternalCoroutinesApi::class)'`

**Comment by kris098e** [comment]
Hi @DavidGrygar

When Mockative generates a mock for a class with a constructor that has dependencies on other classes, then mocks are recursively generated for those dependencies in order to generate a primary constructor for the class.

In your case, since Mockative has to work for all possible classes, then a mock class for `classB` with a primary constructor is generated, which is used in the constructor for the mock-class for `classA`.

---
Mocking an interface is of course much easier, as this does not have any dependencies, and therefore the dependencies are not generated.

**Comment by riQQ** [comment]
Right now the constructor selected by mockative is not necessarily the primary constructor. See https://github.com/mockative/mockative/issues/115#issue-2295572819.

**Comment by kris098e** [comment]
Correct, it is always generated.

**Comment by riQQ** [comment]
I have updated my comment above as I misunderstood your first comment.

**Comment by DavidGrygar** [comment]
@kris098e so it is not bug but feature right?

**Comment by kris098e** [comment]
@DavidGrygar

It is working as intended yes. 
But of course, if you think it can be improved I/we are open for discussing other solutions - but not necessarily coding it ourselves 😃
