### ISSUE TITLE
Cannot use 'R' as reified type parameter. Use a class instead.

### ISSUE THREAD

**Issue by mustafaozhan** [mockative/mockative#20]
Hello 👋 

I start using `mockative` for my KMP project and everything is going fine.

Today, I get stuck with the following error
```
e: /Users/runner/work/CCC/CCC/common/build/generated/ksp/iosTest/kotlin/com/github/mustafaozhan/ccc/common/db/sql/CurrencyQueriesMock.kt: (13, 216): Cannot use 'R' as reified type parameter. Use a class instead.
e: /Users/runner/work/CCC/CCC/common/build/generated/ksp/iosTest/kotlin/com/github/mustafaozhan/ccc/common/db/sql/OfflineRatesQueriesMock.kt: (8, 216): Cannot use 'R' as reified type parameter. Use a class instead.
```

I was trying to mock the `Queries` that is generated with [sqldelight](https://github.com/cashapp/sqldelight)

The relevant PR: Oztechan/CCC#354
You can find also the logs in GitHub checks

**Comment by Nillerr** [comment]
Hi @mustafaozhan 👋

Thanks for using Mockative! You seem to have uncovered an edge case, and my investigation reveals that the culprit is actually this function of the `Transactor` type in SQLDelight:

```kotlin
fun <R> transactionWithResult(
  noEnclosing: Boolean = false,
  bodyWithReturn: TransactionWithReturn<R>.() -> R
): R
```

It turns out that Mockative fails to resolve the invocation of an internal call given a member where the return value is one of the member's generic type parameters. I have submitted a pull request in #21 that addresses this issue, which we're merging as soon as it passes checks, with a release of `v1.1.3` coming very soon.

**Comment by mustafaozhan** [comment]
@Nillerr Thank you for the explanation and the quick update 🙂

**Comment by mustafaozhan** [comment]
Hey @Nillerr thank you for the quick update, maybe due to some catching I was not able to use `v1.1.3` yesterday but I confirm now it works 🎉
