### ISSUE TITLE
How do we mock extension functions?

### ISSUE THREAD

**Issue by AlexandreBrown** [mockative/mockative#49]
Hello, I'm trying to mock an extension function from a third party library (see https://github.com/Kotlin/kotlindl/blob/8a2c5feb0841082703080ab378ca04ed3eec33da/impl/src/commonMain/kotlin/org/jetbrains/kotlinx/dl/impl/preprocessing/OperationEx.kt#L30 )
  
I'm not sure how to do it using **Mockative** v`1.2.6`.  
I tried using `invocation` syntax but it gives me the following error :  
```kotlin
        @Mock
	private val preprocessingPipeline = mock(classOf<Operation<Image<Int>, Image<Int>>>())

	@Mock
	private val imageOperation = mock(classOf<Operation<Image<Int>, Pair<FloatArray, TensorShape>>>())

...
"my test" {
    given(preprocessingPipeline).invocation { call(imageOperation) }
				.thenReturn(imageOperation)
}
```
```kotlin
java.lang.NullPointerException
	at io.mockative.Mockable.record$mockative(Mockable.kt:164)
	at io.mockative.GivenBuilder.invocation(GivenBuilder.kt:17)
```

**Comment by Nillerr** [comment]
Hi @AlexandreBrown 

Since Mockative works by generating a mockable implementation of an interface it can only mock members of that interface, which extensions are not.

Extension functions in Kotlin are actually compiled to something like this:

```kotlin
fun <I, M, O> call(receiver: Operation<I, M>, operation: Operation<M, O>): Operation<I, O>
```

And whenever you reference them in your code, you're not referencing a function on the type of the receiver, but referencing a static function where the first argument is an instance of the receiver. A call to the above function is compiled to something like this:

```kotlin
fun configure(operation: Operation<I, M>, other: Operation<M, O>) {
    OperationExtKt.call(operation, other)
}
```

Since you're effectively referencing a static function, there's no way to generate code that allows intercepting this call in a non-invasive way.

**Comment by AlexandreBrown** [comment]
Thanks a lot @Nillerr , unfortunately since this is not code I can modify I am forced to use it as is.
But your explanations are clear and I understand why Mockative cannot mock it.

I decided to wrap this `call` inside another class so that I can mock it using Mockative.

Thanks a lot.
